# Generated by Django 6.0.3 on 2026-04-26 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_characterprofile_last_activity_on_and_more'),
        ('habits', '0001_initial'),
        ('quests', '0002_quest_xp_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('habit_completed', 'Habit Completed'), ('habit_missed', 'Habit Missed'), ('quest_completed', 'Quest Completed'), ('quest_failed', 'Quest Failed')], max_length=32)),
                ('xp_delta', models.IntegerField()),
                ('total_xp_after', models.PositiveIntegerField()),
                ('level_after', models.PositiveIntegerField()),
                ('streak_after', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('local_date', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='habits.habit')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='characters.characterprofile')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='quests.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='progression_user_id_f805b3_idx'), models.Index(fields=['event_type', 'local_date'], name='progression_event_t_d00575_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('habit__isnull', False), ('quest__isnull', False), _connector='OR'), name='progress_event_has_source')],
            },
        ),
    ]
