# Generated by Django 6.0.3 on 2026-04-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='last_activity_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
