# Generated by Django 6.0.3 on 2026-04-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='xp_reward',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
